import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Brand kit documentation (interactive guide helpers, not app code):
    "docs/brand-kit/**",
    // Claude Code session artifacts (agent worktrees are full repo copies):
    ".claude/**",
    // The design-sync import (#241). `.design-sync/**` is tracked; `ds-bundle/`
    // and `.ds-sync/` are gitignored but eslint does not read `.gitignore`, so
    // they still turn up in a local `eslint .`. All three are generated by an
    // external tool and regenerated on the next sync, so fixing their `any`s by
    // hand would be undone — and leaving them linted made `main` red the moment
    // #241 merged, which stops CI before it reaches Playwright.
    ".design-sync/**",
    "ds-bundle/**",
    ".ds-sync/**",
    // Generated coverage report. Istanbul's HTML bundles ship their own
    // eslint-disable headers, which this config then reports as unused —
    // two warnings on every local run, from files nobody wrote.
    "coverage/**",
  ]),
]);

export default eslintConfig;
