import { camelotColor } from "@/lib/music/camelot-colors"
import { keyTable } from "@/lib/tools/harmonic-tools"

/**
 * The Camelot wheel as a standalone SVG, for "camelot wheel free download".
 *
 * Generated at build from the same converters and palette the interactive
 * wheel uses (`components/tools/camelot-wheel.tsx`), so the downloadable
 * picture cannot disagree with the tool. Language-neutral on purpose: Camelot
 * codes, Open Key codes and the short musical spellings are the same in both
 * languages, and leaving the words "minor"/"major" out is what lets one file
 * serve both pages.
 *
 * A string rather than a React tree because the consumer is a route handler
 * that serves `image/svg+xml`, and a hand-built string is the whole of what
 * that needs — no renderer, no dependency.
 */

const SIZE = 900
const CENTRE = SIZE / 2
const OUTER_RADIUS = 340
const INNER_RADIUS = 225
const OUTER_DOT = 54
const INNER_DOT = 44

/** 12 o'clock is 1, clockwise, like a clock face — the convention every wheel uses. */
function position(num: number, radius: number): { x: number; y: number } {
  const angle = ((num - 3) * 30 * Math.PI) / 180

  return {
    x: CENTRE + radius * Math.cos(angle),
    y: CENTRE + radius * Math.sin(angle),
  }
}

function escape(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

export function renderCamelotWheelSvg(): string {
  const rows = keyTable()
  const byCode = new Map(rows.map((row) => [row.camelot, row]))

  const dots = rows
    .map((row) => {
      const num = Number.parseInt(row.camelot, 10)
      const ring = row.camelot.endsWith("B") ? "B" : "A"
      const radius = ring === "B" ? OUTER_RADIUS : INNER_RADIUS
      const dot = ring === "B" ? OUTER_DOT : INNER_DOT
      const { x, y } = position(num, radius)
      const colour = camelotColor(row.camelot) ?? "#6A5CF0"
      const label = byCode.get(row.camelot)?.abbreviation ?? row.camelot

      return [
        `<g>`,
        `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${dot}" fill="${colour}" stroke="rgba(255,255,255,0.35)" stroke-width="2"/>`,
        `<text x="${x.toFixed(1)}" y="${(y - 4).toFixed(1)}" text-anchor="middle" font-family="ui-monospace, Menlo, Consolas, monospace" font-size="${ring === "B" ? 24 : 20}" font-weight="700" fill="#FFFFFF">${escape(row.camelot)}</text>`,
        `<text x="${x.toFixed(1)}" y="${(y + 18).toFixed(1)}" text-anchor="middle" font-family="ui-monospace, Menlo, Consolas, monospace" font-size="${ring === "B" ? 17 : 15}" fill="rgba(255,255,255,0.92)">${escape(label)}</text>`,
        `<text x="${x.toFixed(1)}" y="${(y + 36).toFixed(1)}" text-anchor="middle" font-family="ui-monospace, Menlo, Consolas, monospace" font-size="12" fill="rgba(255,255,255,0.7)">${escape(row.openKey)}</text>`,
        `</g>`,
      ].join("")
    })
    .join("\n")

  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}" role="img" aria-labelledby="title desc">`,
    `<title id="title">Camelot wheel</title>`,
    `<desc id="desc">The 24 keys in Camelot notation: outer ring B is major, inner ring A is minor. Each position shows the Camelot code, the musical key and the Open Key code. Generated by energycurve.app from the same table its DJ set analyser uses.</desc>`,
    `<rect width="${SIZE}" height="${SIZE}" fill="#08050F"/>`,
    `<circle cx="${CENTRE}" cy="${CENTRE}" r="${OUTER_RADIUS + OUTER_DOT + 14}" fill="none" stroke="rgba(255,255,255,0.08)" stroke-width="1"/>`,
    `<circle cx="${CENTRE}" cy="${CENTRE}" r="${(OUTER_RADIUS + INNER_RADIUS) / 2}" fill="none" stroke="rgba(255,255,255,0.08)" stroke-width="1"/>`,
    dots,
    `<text x="${CENTRE}" y="${CENTRE - 10}" text-anchor="middle" font-family="ui-sans-serif, system-ui, sans-serif" font-size="22" font-weight="700" fill="#FFFFFF">Camelot wheel</text>`,
    `<text x="${CENTRE}" y="${CENTRE + 16}" text-anchor="middle" font-family="ui-sans-serif, system-ui, sans-serif" font-size="14" fill="rgba(255,255,255,0.6)">B = major · A = minor</text>`,
    `<text x="${CENTRE}" y="${CENTRE + 38}" text-anchor="middle" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" fill="rgba(255,255,255,0.45)">energycurve.app</text>`,
    `</svg>`,
  ].join("\n")
}
